language: python
python:
- "3.6"
# setup environment
env:
- DJANGO_VERSION=2.0.2
# install dependencies
install:
- pip install -r requirements.txt
# run test scripts
script:
- python manage.py makemigrations --settings=mmpl_rest.settings
- python manage.py migrate
- python manage.py collectstatic --noinput --settings=mmpl_rest.settings
- coverage run --source=. manage.py test --noinput --settings=mmpl_rest.settings
# run coveralls after successful tests
after_success:
- coveralls